Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like: a) Addition of 2 in all the element  b) Multiply 3 with all the elements c) Divide every element by 2

In [2]:
import numpy as np
q1=np.array([10,100,1000,10000,100000])
print(q1+2)
print(q1*3)
print(q1/5)

[    12    102   1002  10002 100002]
[    30    300   3000  30000 300000]
[2.e+00 2.e+01 2.e+02 2.e+03 2.e+04]


Q.2 Questions on Basic NumPy Array:                                                                        a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])                                           b) Find the most frequent value and their indice(s) in the following arrays:                             i. x = np.array([1,2,3,4,5,1,2,1,1,1]) ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [5]:
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
xfreq=np.bincount(x).argmax()
xi=np.where(x==xfreq)
yfreq=np.bincount(y).argmax()
yi=np.where(y==yfreq)
print(xfreq,"pos",xi)
print(yfreq,"pos",yi)# 1 and 3 both occur same times but one comes/occurs first


[5 4 6 3 2 1]
1 pos (array([0, 5, 7, 8, 9]),)
1 pos (array([0, 1, 2]),)


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows: a) Access 1st row, 2nd column  b) Access 3rd row, 1st column

In [7]:
arr=np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print(arr[0,1])
print(arr[2,0])

20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [12]:
rhythm=np.linspace(10,100,25)
print(rhythm)
print(rhythm.shape)
print(rhythm.size)
print(rhythm.ndim)
print(rhythm.dtype)
print(rhythm.nbytes)
print(rhythm.reshape(-1,1))
print(rhythm.T)#this requires two dimensions to swap

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
(25,)
25
1
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.

In [17]:
ucs420_rhythm = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])
print(ucs420_rhythm.shape)
print(np.mean(ucs420_rhythm))
print(np.median(ucs420_rhythm))
print(np.min(ucs420_rhythm))
print(np.max(ucs420_rhythm))
print(np.unique(ucs420_rhythm))
reshaped_ucs420_rhythm=ucs420_rhythm.reshape(4,3)
print(reshaped_ucs420_rhythm)
resized_ucs420_rhythm=np.resize(ucs420_rhythm,(2,3))
print(resized_ucs420_rhythm)
resized_ucs420_rhythm=np.resize(ucs420_rhythm,(2,8))
print(resized_ucs420_rhythm)


(3, 4)
43.333333333333336
37.5
10
90
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
[[10 20 30 40 50 60 70 80]
 [90 15 20 35 10 20 30 40]]
